export const events = [
   {
      image: "/images/event1.png",
      title: "React Summit 2025",
      slug: "react-summit-2025",
      date: "Jan 25, 2025",
      time: "10:00 AM - 4:00 PM",
      location: "San Francisco, CA, USA",
   },
   {
      image: "/images/event2.png",
      title: "Next.js Conf 2025",
      slug: "nextjs-conf-2025",
      date: "Feb 10, 2025",
      time: "9:00 AM - 5:00 PM",
      location: "New York, NY, USA",
   },
   {
      image: "/images/event3.png",
      title: "Fullstack Hackathon",
      slug: "fullstack-hackathon-2025",
      date: "Mar 5-7, 2025",
      time: "12:00 PM - 11:00 PM",
      location: "Berlin, Germany",
   },
   {
      image: "/images/event4.png",
      title: "AI & ML Meetup",
      slug: "ai-ml-meetup-2025",
      date: "Apr 15, 2025",
      time: "6:00 PM - 9:00 PM",
      location: "London, UK",
   },
   {
      image: "/images/event5.png",
      title: "JavaScript Conference",
      slug: "javascript-conference-2025",
      date: "May 20-22, 2025",
      time: "9:00 AM - 4:00 PM",
      location: "Toronto, Canada",
   },
   {
      image: "/images/event6.png",
      title: "Frontend Masters Workshop",
      slug: "frontend-masters-workshop-2025",
      date: "Jun 12, 2025",
      time: "1:00 PM - 6:00 PM",
      location: "Austin, TX, USA",
   },
];
